### ISSUE TITLE
Beyaz Ekran

### ISSUE THREAD

**Issue by yasincetin002** [otabakoglu/ListApp#1]
Uygulamayı derleyip sıfırdan kurulum yaptığımızda beyaz ekran ile karşılaştık.
<img width="336" alt="Screen Shot 2022-09-14 at 16 56 22" src="https://user-images.githubusercontent.com/28646520/190393866-fd7d80d0-ecf0-41bf-a3ec-1571f8a1295f.png">

**Comment by otabakoglu** [comment]
Teşekkürler, 
Repo içine collect {} fonksiyonu eklendi.
